# Generated by Django 5.1.4 on 2024-12-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('type', models.CharField(choices=[('AP', 'Appetizers'), ('SD', 'Salads'), ('WP', 'Wraps'), ('SW', 'Sandwiches'), ('PT', 'Pastas'), ('BG', 'Beverages'), ('PZ', 'Pizzas'), ('MC', 'Main_Courses'), ('BF', 'Breakfast'), ('DS', 'Desserts'), ('SN', 'Snacks')], max_length=2)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='images/food_items/')),
                ('price', models.IntegerField()),
            ],
        ),
        
    ]
