# Generated by Django 5.1.4 on 2024-12-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_food_item_remove_menuitem_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_item',
            name='type',
            field=models.CharField(choices=[('SD', 'Salads'), ('WP', 'Wraps'), ('MC', 'Main_Courses'), ('SN', 'Snacks'), ('DS', 'Desserts'), ('BG', 'Burgers'), ('BF', 'Breakfast'), ('AP', 'Appetizers'), ('PT', 'Pastas'), ('PZ', 'Pizzas'), ('BV', 'Beverages'), ('SW', 'Sandwiches')], max_length=2),
        ),
    ]
