# Generated by Django 5.1.4 on 2024-12-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_food_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_item',
            name='type',
            field=models.CharField(choices=[('AP', 'Appetizers'), ('SD', 'Salads'), ('WP', 'Wraps'), ('SW', 'Sandwiches'), ('PT', 'Pastas'), ('BG', 'Burgers'), ('PZ', 'Pizzas'), ('MC', 'Main_Courses'), ('BF', 'Breakfast'), ('DS', 'Desserts'), ('BV', 'Beverages'), ('SN', 'Snacks')], max_length=2),
        ),
    ]
