# Generated by Django 5.1.4 on 2024-12-27 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_bookings_alter_food_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bookings',
            name='final_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bookings',
            name='items',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bookings',
            name='name',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='bookings',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
