# Generated by Django 5.1.4 on 2024-12-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_bookings_booking_date_bookings_final_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=122)),
                ('month', models.CharField(default='', max_length=12)),
                ('image', models.ImageField(upload_to='images/books/')),
                ('desc', models.TextField(default='')),
            ],
        ),
    ]
