# Generated by Django 5.1.4 on 2024-12-28 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='bookings',
            new_name='Booking',
        ),
    ]
