# Generated by Django 5.1.4 on 2024-12-28 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='month',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
