# Generated by Django 5.1.4 on 2024-12-28 18:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_bookclubregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=122)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField()),
                ('image', models.ImageField(upload_to='images/books/')),
                ('desc', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=122)),
                ('email', models.CharField(default='', max_length=122)),
                ('phone', models.CharField(default='', max_length=12)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.event')),
            ],
        ),
    ]
